# Rename this to keys.py if running locally,
# and replace the API keys with your own information.
# This project uses an EC2 instance with
# Elasticache providing the redis broker and an
# RDS instance of postgresql.


EMAIL_HOST_USER = 'YOUR_EMAIL_ADDRESS@gmail.com'
EMAIL_HOST_PASSWORD = 'YOUR_EMAIL_PASSWORD'
SETTINGS_KEY = 'YOUR_SETTINGS_KEY'
SITE_URL = 'LOCALHOST_OR_YOUR_URL'
TWILIO_SID = 'YOUR_TWILIO_SID'
TWILIO_TOKEN = 'YOUR_TWILIO_TOKEN'
SERVER_NUMBER = 'YOUR_TWILIO_NUMBER'
TWILIO_CALLBACK_URL = 'http://YOUR_SITE_URL.com/api/calls/call_data/'
TWITTER_CONS_KEY = 'YOUR_TWITTER_CONSUMER_KEY'
TWITTER_SECRET = 'YOUR_TWITTER_SECRET_KEY'
TWITTER_TOKEN_KEY = 'YOUR_TWITTER_TOKEN_KEY'
TWITTER_TOKEN_SECRET = 'YOUR_TWITTER_TOKEN_SECRET'
TWITTER_SCREEN_NAME = 'YOUR_TWITTER_HANDLE'

POSTGRES_PW = 'YOUR_POSTGRES_PASSWORD'
POSTGRES_USER = 'YOUR_POSTGRES_USER'
POSTGRES_NAME = 'YOUR_POSTGRES_NAME'
POSTGRES_HOST = 'YOUR_POSTGRES_AWS_URL'
POSTGRES_PORT = 'YOUR_POSTGRES_PORT'